version: '3.9'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: zznk
      MYSQL_DATABASE: ecuador
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - appnet    

  app1:
    build: .
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=zznk
      - MYSQL_DB=ecuador
    networks:
      - appnet

  app2:
    build: .
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=zznk
      - MYSQL_DB=ecuador
    networks:
      - appnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
    networks:
      - appnet

volumes:
  mysql-data:

networks:
  appnet:
    driver: bridge
